# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==21.10b0 numpy pylorentz pytest pytest-cov
    - name: Lint with black
      run: |
        black --check helicity_param/**
        black --check test/**
    - name: Unit Test
      run: |
        pytest test/ut/test_ut.py --cov=./ --cov-report=xml:ut.xml
    - name: Integration Test
      run: |
        pip install phasespace
        pytest test/it/test_it.py --cov=./ --cov-report=xml:it.xml
    - name: Validation
      run: |
        pip install matplotlib
        pytest test/script/validation.py --cov=./ --cov-report=xml:validation.xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        files: ut.xml,it.xml,validation.xml
    - name: Upload Plots
      uses: actions/upload-artifact@v2
      with:
        name: phsp-plot
        path: helicity_phsp.png
